# Generated by Django 4.1 on 2022-09-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_companyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='email_address',
        ),
    ]
