# Generated by Django 4.1 on 2022-09-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_companyinfo_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='phone_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
