# Generated by Django 4.1 on 2022-09-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_companyinfo_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
