# Generated by Django 4.1 on 2022-09-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_about_delete_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Phone', models.IntegerField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
