# Generated by Django 4.1 on 2022-09-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_companyinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='name',
            new_name='company',
        ),
    ]
