# Generated by Django 4.1 on 2022-09-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_name_companyinfo_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='Phone',
            new_name='phone',
        ),
    ]
