# Generated by Django 4.1 on 2022-09-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_phone_companyinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='company',
            field=models.CharField(max_length=100),
        ),
    ]
