# Generated by Django 4.1 on 2022-09-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_companyinfo_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=500)),
                ('ofdetails', models.CharField(max_length=1000)),
            ],
        ),
    ]
