# Generated by Django 4.1 on 2022-09-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_floeabout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
